### ISSUE TITLE
Map instantly?

### ISSUE THREAD

**Issue by tomek-he-him** [mattdesl/new-array#1]
Very often I find myself creating an array of some dummy values just to map over it.

I know that would be a breaking change – but what do you think of an instant map API? If the second arg is a function, it’d be called on every item instead of being used as a value.

So these two would be equivalent:

``` js
array(5).map(() => document.createElement('div'));

array(5, () => document.createElement('div'));
```

**Comment by tomek-he-him** [comment]
Saving 4 characters by swapping `).map(` with `,` doesn’t seem much of a deal – but to me it does make the thing more readable.

**Comment by mattdesl** [comment]
It sounds like a different module. I have been using this for the second parameter, like so:

``` js
var array = require('new-array')

// scratch image buffer
var pixels = array(width * height * 3, 0xff)
```

Changing the second parameter would change the purpose of this module. :smile:

**Comment by tomek-he-him** [comment]
I thought it’d work as it does unless the second param is a function.

But yeah, :+1:. Explicit is better than implicit.

**Comment by tomek-he-him** [comment]
> I have been using this for the second parameter

BTW, I thought you also usually mapped stuff – since the module is

> Primarily motivated by the fact that new Array(n) […] does not play well with methods like Array#map().

**Comment by mattdesl** [comment]
Yup, but sometimes it can be nice to avoid an unnecessary closure and array copy. But maybe JITs optimize it away these days, who knows.
